// This file was generated by Prisma
import { defineConfig } from "prisma/config";

export default defineConfig({
  schema: "prisma/models",
  migrations: {
    path: "prisma/migrations",
  },
  datasource: {
    url: process.env.DATABASE_URL || "postgresql://localhost:5432/db",
  },
});
